= Antora Demo Site and Playbook Project
// :idprefix:
// :idseparator: -
// URIs:
:uri-project: https://antora.org
:uri-org: https://github.com/banshee77
:uri-repo: {uri-org}/antora-docs-site
:uri-demo-playbook: {uri-repo}/blob/master/antora-playbook.yaml
:uri-antora-docs: https://docs.antora.org/antora/latest
:uri-docs-install: {uri-antora-docs}/install/install-antora/
:uri-docs-playbook: {uri-antora-docs}/playbook/playbook-schema/
:uri-docs-run: {uri-antora-docs}/run-antora/

This is the playbook project for the Antora demonstration site.

To generate the demo site using this playbook project and the demo documentation sites, you'll need to {uri-docs-install}[install the Antora CLI and default site generator].

== Playbook

An {uri-docs-playbook}[Antora playbook] is responsible for generating a documentation site.
It contains the instructions a user wants to relay to an Antora site generator pipeline.
These instructions include the content Antora should collect and the UI it should apply to the generated site.

The file [.path]_antora-playbook.yaml_ in this repository is the playbook used to produce the demo site.
It tells Antora where to find the Site A and Site B remote content repositories and default UI.

== Generate the Demo Site

Once you've installed Antora and {uri-demo-playbook}[saved the demo playbook] ([.path]_antora-playbook.yaml_) to a local directory, you're ready to {uri-docs-run}[run Antora].