= Antora Demo Site and Playbook Project
// :idprefix:
// :idseparator: -
// URIs:
:uri-project: https://antora.org
:uri-docs: https://docs.antora.org
:uri-org: https://github.com/banshee77
:uri-repo: {uri-org}/antora-docs-site
:uri-demo-playbook: {uri-repo}/blob/master/antora-playbook.yaml
:uri-antora-docs: https://docs.antora.org/antora/latest
:uri-docs-install: {uri-antora-docs}/install/install-antora/
:uri-docs-playbook: {uri-antora-docs}/playbook/playbook-schema/
:uri-docs-run: {uri-antora-docs}/run-antora/

This is the playbook project for the Antora demonstration site.

To generate the demo site using this playbook project and the demo documentation sites, you'll need to install the Antora CLI.

----
npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3
antora -v
----

== Playbook

An {uri-demo-playbook}[Antora playbook] is responsible for generating a documentation site.
It contains the instructions a user wants to relay to an Antora site generator pipeline.
These instructions include the content Antora should collect and the UI it should apply to the generated site.

The file [.path]_antora-playbook.yaml_ in this repository is the playbook used to produce the demo site.
It tells Antora where to find the Site A and Site B remote content repositories and default UI.

== Generate the Demo Site

Clone repository and run Antora

----
git clone https://github.com/banshee77/antora-docs-site.git

cd antora-docs-site

antora antora-playbook.yaml
----

output:
----
----

Open demo site in the browser:

----
start build\site\index.html
----

== Run Demo Site on Local Server

Install the http-server package globally using npm:

----
node -v

npm i -g http-server

http-server build/site -c-1 -p5000
----

output similar to:

----
Starting up http-server, serving build/site

http-server version: 14.0.0

http-server settings: 
CORS: disabled
Cache: -1 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://192.168.99.1:5000
  http://127.0.0.1:5000
Hit CTRL-C to stop the server
----


== Resources

* {uri-project}[Antora Project]
* {uri-docs}[Antora Docs]
